# -*- coding: utf-8 -*-
"""mason_google_autosuggest_a-z.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jserAu2uiPUJ9TGKneHzSkO_UTsTjmgd
"""

import os, requests, json
import requests, json
import string
import time

headers = {
    "User-Agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19582"
}
# client param could be replaced with firefox or other browser
def scrape_google_autosuggest(query):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
    response = requests.get(f'http://google.com/complete/search?client=chrome&q={query}', headers=headers)
    return json.loads(response.text)[1]

def main():
    base_query = input('Enter Base Query ')
    alphabet = string.ascii_lowercase  # Contains all lowercase letters 'a' to 'z'

    for letter in alphabet:
        query = base_query + letter
        results = scrape_google_autosuggest(query)
        for result in results:
            print(result)

        # Sleep for a few seconds to avoid overloading Google's servers
        time.sleep(2)

if __name__ == "__main__":
    main()
